// 한글 폰트를 사용하기 위해 Noto Sans KR을 불러옵니다.
import { Noto_Sans_KR } from "next/font/google";
import type { Metadata } from "next";

import "@/styles/globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

// Noto Sans KR 폰트를 설정 합니다.
const noto_sans_kr = Noto_Sans_KR({
  variable: "--font-noto-sans-kr",
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* 요소들에 한글 폰트 제공 */}
      <body className={`${noto_sans_kr.variable} bg-white text-black`}>
        <Header />
        {children}
        <Footer /> {/* Footer */}
      </body>
    </html>
  );
}
